yandex-cloud-resourcemanager:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-resourcemanager/mcp-yandex-cloud-resourcemanager"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
    YC_INSECURE: "1"
  description: "Manage resource hierarchy: clouds, folders, and organizations"
  tags:
    - resourcemanager
    - folders
    - clouds
    - organization

yandex-cloud-compute:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-compute/mcp-yandex-cloud-compute"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
    YC_INSECURE: "1"
  description: "Manage compute instances, images, disks, and snapshots in Yandex Cloud"
  tags:
    - compute
    - vm
    - instances
    - disks
    - snapshots

yandex-cloud-vpc:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-vpc/mcp-yandex-cloud-vpc"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
    YC_INSECURE: "1"
  description: "Manage virtual networks, subnets, routes, and security groups"
  tags:
    - vpc
    - network
    - subnet
    - routing
    - security-groups

yandex-cloud-serverless:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-serverless/mcp-yandex-cloud-serverless"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
  description: "Manage serverless functions, API gateways, and containers"
  tags:
    - serverless
    - functions
    - api-gateway
    - containers
    - faas

yandex-cloud-iam:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-iam/mcp-yandex-cloud-iam"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
  description: "Manage IAM policies, roles, service accounts, and access bindings"
  tags:
    - iam
    - access
    - roles
    - service-accounts
    - permissions

yandex-cloud-ydb:
  command: "/Users/depdiller/mcp-servers/servers/mcp-yandex-cloud-ydb/mcp-yandex-cloud-ydb"
  args:
    - --transport
    - stdio
  env:
    ACCESS_TOKEN: "y0__xDF9_Q-GMHdEyDjgteSEwns1DjnAaTnlsujPnB5cbsbsCCb"
  description: "Manage distributed YDB databases, tables, and queries"
  tags:
    - ydb
    - database
    - distributed
    - nosql
    - tables
  tools: []
