[project]
name = "utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-mcp-adapters<=0.1.9",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.10.1",
]
