vectordb:
  - name: chroma_sentence_transformers
    db_type: chroma
    client_type: persistent
    embedding_model: yandex_sentence_transformers
    collection_name: sentence_transformers
    path: resources/chroma
#  - name: chroma_openai_small
#    db_type: chroma
#    client_type: persistent
#    embedding_model: yandex_openai
#    collection_name: openai_small
#    path: resources/chroma
node_lines:
  - node_line_name: retrieve_node_line  # Arbitrary node line name
    nodes:
      - node_type: retrieval
        strategy:
#          metrics: [ retrieval_f1, retrieval_recall, retrieval_precision, retrieval_ndcg, retrieval_map, retrieval_mrr ]
          metrics: [ retrieval_recall, retrieval_precision, retrieval_mrr ]
          speed_threshold: 10
        top_k: 25
        modules:
          - module_type: vectordb
            vectordb: chroma_sentence_transformers
#          - module_type: vectordb
#            vectordb: chroma_openai_small
      - node_type: passage_reranker
        strategy:
          metrics: [ retrieval_recall, retrieval_precision, retrieval_mrr ]
          speed_threshold: 10
        top_k: 5
        modules:
          - module_type: pass_reranker
#          - module_type: tart
#          - module_type: monot5
#          - module_type: upr
#          - module_type: colbert_reranker
#          - module_type: sentence_transformer_reranker
          - module_type: flag_embedding_reranker
          - module_type: flag_embedding_llm_reranker
          - module_type: openvino_reranker
          - module_type: flashrank_reranker
  - node_line_name: post_retrieve_node_line  # Arbitrary node line name
    nodes:
      - node_type: prompt_maker
        strategy:
          metrics:
            - metric_name: bleu
#            - metric_name: meteor
            - metric_name: rouge
            - metric_name: sem_score
              embedding_model: yandex_sentence_transformers
          speed_threshold: 10
          generator_modules:
            - module_type: llama_index_llm
              llm: anthropic
              model: claude-sonnet-4-20250514
              base_url: https://api.eliza.yandex.net/raw/anthropic
              api_key: y1__xDl3MSRpdT-ARiuKyCc4dgCI97IX01agJKQ2rqtN3U7oV5CCeQ
        modules:
          - module_type: fstring
            prompt: "Answer the following question about Yandex Cloud infrastructure: how to {query}? \n.
            Info to retrieve answer from: {retrieved_contents} \n. Give as answer ONLY on word - name of tool you would
            use too solve given problem? Tool name must be retrieved from given context, if you cannot find correct tool
            there just answer - NONE."
      - node_type: generator
        strategy:
          metrics:
            - metric_name: bleu
#            - metric_name: meteor
            - metric_name: rouge
            - metric_name: sem_score
              embedding_model: yandex_sentence_transformers
#              embedding_model: yandex_openai
          speed_threshold: 10
        modules:
          - module_type: llama_index_llm
            llm: anthropic
            model: claude-sonnet-4-20250514
            base_url: https://api.eliza.yandex.net/raw/anthropic
            api_key: y1__xDl3MSRpdT-ARiuKyCc4dgCI97IX01agJKQ2rqtN3U7oV5CCeQ